/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../api/api`; params?: Router.UnknownInputParams; } | { pathname: `/FizetesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginLogout`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CartContext` | `/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Kosár` | `/Kosár`; params?: Router.UnknownInputParams; } | { pathname: `/../auth/AuthProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../components/external-link`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Listazo` | `/Listazo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../api/api`; params?: Router.UnknownOutputParams; } | { pathname: `/FizetesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginLogout`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CartContext` | `/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Kosár` | `/Kosár`; params?: Router.UnknownOutputParams; } | { pathname: `/../auth/AuthProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/external-link`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/collapsible`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Listazo` | `/Listazo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../api/api${`?${string}` | `#${string}` | ''}` | `/FizetesScreen${`?${string}` | `#${string}` | ''}` | `/LoginLogout${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CartContext${`?${string}` | `#${string}` | ''}` | `/CartContext${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Kosár${`?${string}` | `#${string}` | ''}` | `/Kosár${`?${string}` | `#${string}` | ''}` | `/../auth/AuthProvider${`?${string}` | `#${string}` | ''}` | `/../components/external-link${`?${string}` | `#${string}` | ''}` | `/../components/ui/collapsible${`?${string}` | `#${string}` | ''}` | `/../constants/theme${`?${string}` | `#${string}` | ''}` | `/../hooks/use-color-scheme${`?${string}` | `#${string}` | ''}` | `/../hooks/use-color-scheme.web${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Listazo${`?${string}` | `#${string}` | ''}` | `/Listazo${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../api/api`; params?: Router.UnknownInputParams; } | { pathname: `/FizetesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginLogout`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CartContext` | `/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Kosár` | `/Kosár`; params?: Router.UnknownInputParams; } | { pathname: `/../auth/AuthProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../components/external-link`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Listazo` | `/Listazo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; };
    }
  }
}
